services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: development
    restart: always
    environment:
      VITE_NODE_ENV: development
      VITE_PORT: 80
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 80:80
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/