services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: development
    restart: always
    environment:
      NODE_ENV: development
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3001
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/